<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"><xsl:output method="xml" version="1.0" encoding="UTF-8" /><xsl:template match="/"><krpano><plugin name="tb_select_1" url="" zorder="99" alpha="1" blendmode="NORMAL" align="left" edge="center" y="0" ox="78" oy="0" width="150" height="56" refreshrate="" scale="1" smoothing="True" mask="" rotate="0" visible="True" enabled="True" capture="False" handcursor="True" keep="True" children="True" preload="False" effect="glow(0x00FFFF,0.7,4,4)" onloaded="set(effect,glow(0xFF0000,0.7,4,4););" /><layer name="c_ly_1_0" keep="true" type="container" align="left" edge="left" width="100%" height="100%" bgcolor="0x000000" parent="scrollarea_1" visible="true"><xsl:for-each select="/Tour/Scene/sceneitem"><layer row="{position()}" name="tb_{@sceneid}_1" url="%FIRSTXML%/scene/{@sceneid}/T.jpg" zorder="100" alpha="0.8" blendmode="NORMAL" align="left" edge="center" x="{(position()-1)*153}" y="0" ox="78" oy="0" width="150" height="56" refreshrate="" scale="1" smoothing="True" mask="" rotate="0" visible="True" enabled="True" capture="True" handcursor="True" keep="True" children="True" preload="False" Intro="" style="" effect="glow(0xFFFFFF,0.7,4,4);" scalechildren="False" crop="" onovercrop="" ondowncrop="" scale9grid="" onover="set(effect,glow(0x00FFFF,0.7,4,4););set(alpha,1);" onhover="showtext('{@title}');" onout="set(effect,glow(0xFFFFFF,0.7,4,4););set(alpha,0.8);" onclick="_loadscene({@sceneid});" ondown="" onup="" onloaded=""><layer name="tb_title_{@sceneid}_1" url="%SWFPATH%/plugins/textfield.swf" zorder="100" alpha="0.8" blendmode="NORMAL" align="bottom" edge="bottom" x="0" y="0" ox="0" oy="0" width="100%" height="20" refreshrate="" scale="1" smoothing="True" mask="" rotate="0" visible="True" enabled="True" capture="True" handcursor="True" keep="True" children="True" preload="False" Intro="" style="" effect="" scalechildren="True" crop="" onovercrop="" ondowncrop="" scale9grid="" onover="" onhover="" onout="" onclick="" ondown="" onup="" onloaded="" html="&lt;html&gt;{@title}&lt;/html&gt;" css="data:tb_title" autosize="center" background="True" backgroundcolor="0x333333" bordercolor="0x000000" borderwidth="0" roundedge="0" selectable="False" glow="0" glowcolor="0xFFFFFF" blur="0" shadow="0" textglow="0" textblur="0" textglowcolor="0xFFFFFF" textshadow="1" devices="flash" /></layer></xsl:for-each></layer><action name="_setthumbs_1"> _show_tb_1(get(Set.TypeID),%1);
      //mul(dst,get(plugin[tb_%1_1].x),-1);
      //add(dst,dst,249);
      //if (dst LT 0,set(dst,0);)
      //tween(plugin[t_group_info].x,get(dst),0.4,linear); </action><action name="_show_tb_1">copy(plugin[tb_select_1].url,layer[tb_%2_1].url);
      copy(plugin[tb_select_1].parent,layer[tb_%2_1].parent);
      copy(plugin[tb_select_1].x,layer[tb_%2_1].x);
      copy(plugin[tb_select_1].y,layer[tb_%2_1].y);
      
      set(_pname_1,get(layer[tb_%2_1].parent));
      set(_p_pname_1,get(layer[get(_pname_1)].parent));
      plugin[get(_p_pname_1)].scrolltocenter(get(plugin[tb_select_1].x),get(plugin[tb_select_1].y));
      
      //set(plugin[container_].visible,true); </action><data name="tb_title">html{color:#FFFFFF;font-family:宋体;font-size:12px;text-align:center;}</data></krpano></xsl:template></xsl:stylesheet>